// <auto-generated />
namespace DiemdanhHocvien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_studentId_tblAttendence : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_studentId_tblAttendence));
        
        string IMigrationMetadata.Id
        {
            get { return "202111171613391_create_studentId_tblAttendence"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
