// <auto-generated />
namespace DiemdanhHocvien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class class_del_col_phone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(class_del_col_phone));
        
        string IMigrationMetadata.Id
        {
            get { return "202111160302318_class_del_col_phone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
