// <auto-generated />
namespace DiemdanhHocvien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_classid_for_attendance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_classid_for_attendance));
        
        string IMigrationMetadata.Id
        {
            get { return "202111210907502_create_classid_for_attendance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
